# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0003_auto_20180327_1317'),
        ('users', '0002_tagmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('blog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogModel', verbose_name='博客名')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TagModel', verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签属性',
                'verbose_name_plural': '标签属性',
            },
        ),
    ]
