# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180327_1317'),
        ('users', '0002_tagmodel'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagpropertymodel',
            name='blog_name',
        ),
        migrations.RemoveField(
            model_name='tagpropertymodel',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='tagpropertymodel',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogModel', verbose_name='博客'),
        ),
        migrations.AddField(
            model_name='tagpropertymodel',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.TagModel', verbose_name='标签'),
        ),
    ]
