# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_tagmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='blog',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
