# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-29 10:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180329_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxmodel',
            name='box_content',
            field=ckeditor.fields.RichTextField(verbose_name='box内容'),
        ),
    ]
