# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180327_1405'),
        ('users', '0002_tagmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
